package com.bn.Sample17_7;

public enum BodyPartIndex {
	
	BODYPART_HEAD,//头
	BODYPART_SPINE,//脊柱
	BODYPART_PELVIS,//骨盆

	BODYPART_LEFT_UPPER_ARM,//左大臂
	BODYPART_RIGHT_UPPER_ARM,//右大臂
	
	BODYPART_LEFT_LOWER_ARM,//左小臂
	BODYPART_RIGHT_LOWER_ARM,//右小臂

	BODYPART_LEFT_UPPER_LEG,//左大腿
	BODYPART_RIGHT_UPPER_LEG,//右大腿
	
	BODYPART_LEFT_LOWER_LEG,//左小腿
	BODYPART_RIGHT_LOWER_LEG,//右小腿

	BODYPART_COUNT;
}
